hhh/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^emailauth/', include('emailauth.urls')),
    url(r'^scraper/', include('scraper.urls')),
    url(r'^', include('recipe.urls')),
]

recipe/urls.py
"""Holds the routing information for the recipe app."""

from django.conf.urls import url

from . import views

app_name = "recipe"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_private_recipe$', views.add_private_recipe, name='add_private_recipe'),
    url(r'^edit_private_recipe/(?P<id>[0-9]+)/$', views.edit_private_recipe, name='edit_private_recipe'),
    url(r'^delete_recipe/(?P<id>[0-9]+)/$', views.delete_recipe_view, name='delete_recipe_view'),
    url(r'^recipe_full_view/(?P<id>[0-9]+)/$', views.recipe_full_view, name='recipe_full_view'),
    url(r'^recipe_full_view/(?P<id>[0-9]+)/rate/$', views.rate, name='rate'),
    url(r'^recipe_full_view/(?P<id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^get_recipes/$', views.get_recipes, name='get_recipes'),
    url(r'^submit_for_public/(?P<id>[0-9]+)/$', views.submit_for_public, name='submit_for_public'),
]

recipe/models.py
"""Holds the recipe models for the database."""

from django.db import models
from django.db.models import Q, QuerySet, Avg
from django.contrib.auth.models import User
from django.utils import timezone
from itertools import chain

class Group(models.Model):
    """This represents a food category.

    Each ingredient has a single category. In the web-app, the ingredients are
    categorized by these groups.
    """

    # The name of the group
    name = models.CharField(max_length=40, unique=True)

    def __str__(self):
        """Return a string to identify the object in the admin app."""
        return self.name


class Ingredient(models.Model):
    """This is an ingredient to recipes.

    Each ingredient may be a part of many recipes and each recipe may have many
    ingredients. The purpose of this class is to provide consistent naming between
    ingredients and easier filtering of recipes by ingredient. Each recipe is a part
    of a group.
    """

    # The group which this ingredient belongs to
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    # The name of this ingredient
    name = models.CharField(max_length=40, unique=True)

    def __str__(self):
        """Return a string to identify the object in the admin app."""
        return self.name

    def get_recipes(self):
        """Return a QuerySet of associated Recipes."""
        return self.recipe_set.values()

    def get_recipe_ids(self):
        """Returns a list of associated Recipe IDs"""
        my_recs = list(self.get_recipes())
        # get just the ids from each record
        rec_ids = [rec['id'] for rec in my_recs]
        return rec_ids


class IngredientUtils():
    """Class of ingredient helper functions.

    Contains methods to help search for recipes by ingredient
    """
    def __init__(self, user_id=0):
        self.user_id = user_id

    def __str__(self):
        return "Ingredient Tools"

    def find_recipes(self, ingredients, start=0, end=200):
        """Returns a QuerySet of Recipes
        Given a list of ingredients and a range, the database
        will be queried to find all recipes with common association
        between the ingredients.

        Once these are found, the range provided will determine how
        many recipes are actually returned.
        """

        recipe_qs = self._make_qs_list(ingredients)
        recipe_list = self._dict_to_qs(recipe_qs)
        # if ingredients were found...
        if len(recipe_list) > 0:
            # slice recipe list
            recipe_list = recipe_list[start:end]
        # return empty queryset
        else:
            emp_qs = Recipe.objects.none()
            recipe_list = list(emp_qs.values())
            # print('Returning:', emp_qs)
        return recipe_list

    def _ingredient_intersect(self, ing_qs_list):
        """Returns a QuerySet of recipes shared between ingredients"""

        #return QuerySet.intersection(*ing_qs_list)
        return QuerySet.union(*ing_qs_list)

    def _filter_private_recs(self, recipe):
        """Returns public recipes and the user's private recipes (if applicable)"""
        #private_q = Q(is_private=False)
        #usr_id_q = Q(user_id=self.user_id)
        ## get public recipes or those that belong to the user
        if not recipe.is_private or recipe.user_id == self.user_id:
            return recipe
        else:
            return None

    def _make_qs_list(self, ingredients):
        """Returns a Dictionary of QuerySets of recipes given a list of ingredient names"

        Given a list of Ingredients, this function will search for recipes
        linked to each ingredient, then sorts them.
        Each recipe is sorted into a bucket based on how many ingredients it contains from the ing_list.
        Buckets are classified by a percentage of ingredients the recipes contain:
            -i.e. ['flour', 'sauce', 'cheese', 'water'] are passed as ingredients. Looking at the "Sausage Pizza" recipe,
            all ingredients, except sausage, are passed in the ingredients list. This recipe would be placed in the 4/5 (80%) bucket
        """

        recipe_dict = {}
        used_recs = [] # list of rec ids that were actually used
        # loop over ingredients, finding recipes associated with
        # each ingredient, then sorting them by percent of ingredients
        for ing in ingredients:
            try:
                cur_ing = Ingredient.objects.get(name=ing)
                rec_ids = cur_ing.get_recipe_ids()
                cur_ing_recs = Recipe.objects.filter(id__in=(rec_ids))
            # if ingredient found, get recipes
                if len(cur_ing_recs) > 0:
                    # get recipe percentages
                    for rec in cur_ing_recs:
                        rec_id = rec.id
                        #print('Recipe:', rec.title, 'RecID:', rec_id)
                        if rec_id in used_recs:
                            pass
                        else:
                            # save rec_id
                            used_recs.append(rec_id)
                            tmp_perc = rec.get_perc_ingredients(ingredients)
                            # filter recipe (skip if private and not the user's)
                            filtered_rec = self._filter_private_recs(rec)
                            if filtered_rec is not None:
                                # add to recipe percent buckets.
                                rec_to_save = list(Recipe.objects.filter(id=filtered_rec.id).values())
                                # add percent to recipe branch
                                rec_to_save[0]['percentage'] = tmp_perc
                                if tmp_perc in recipe_dict:
                                    recipe_dict[tmp_perc].append(rec_to_save)
                                else:
                                    recipe_dict[tmp_perc] = [rec_to_save]
            # else, ingredient does not exist in the database
            except (Ingredient.DoesNotExist):
               continue
        return recipe_dict

    def _get_recipe_range(self, recipe_list, start, end):
        """Returns a slice of a Recipe QuerySet

        NOTE: Currently set to sort by "title". Can be changed to
        whatever we want the recipes to be sorted by.
        """
        return recipe_list[start:end]

    def _dict_to_qs(self, dict):
        """Converts dictionary of recipes into a sorted list"""
        keys = sorted(dict.keys())
        keys.sort(reverse=True)
        out_lst = []

        # for each list of QS's, append it to the out_lst of recipes
        # from greatest to least
        for key in keys:
            out_lst += dict[key]
        # Found this nifty tool on StackOverflow :)
        new_qs = list(chain(*out_lst))
        return new_qs



class Appliance(models.Model):
    """This is an appliance that is required to make a recipe.

    A recipe may
    have 0+ appliances. The purpose of this class is to provide consistent
    naming between appliances and easier filtering of recipes by appliance.
    """

    # The name of this appliance
    name = models.CharField(max_length=40)

    def __str__(self):
        """Return a string to identify the object in the admin app."""
        return self.name


class Recipe(models.Model):
    """This holds all the attributes of a recipe.

    The title and summary display when the recipe is shown as a search result.
    The user is the user that submitted the recipe. The time is measured in minutes.
    The image_url points to either an internal or external image location. The
    rating ranges between zero and five. The ingredients and appliances have a
    many-to-many relationship with a recipe.
    """

    # Title of the recipe
    title = models.CharField(max_length=50)
    # Short summary of the recipe (to be used on preview when searching)
    summary = models.CharField(max_length=280, null=True, blank=True)
    user = models.ForeignKey(
        User, null=True, on_delete=models.SET_NULL)
    DIFFICULTY_CHOICES = (
        ('', '--Difficulty--'),
        ('E', 'Easy'),
        ('M', 'Medium'),
        ('D', 'Hard')
    )
    # The actual difficulty of the recipe
    difficulty = models.CharField(max_length=1, null=True,
                                  choices=DIFFICULTY_CHOICES)
    # The time it takes to make the recipe (in minutes)
    time = models.IntegerField(null=True, blank=True)
    # The image url to be used to showcase the recipe (used in both search and
    # detailed views)
    image_url = models.CharField(max_length=200, null=True, blank=True)
    # The detailed instructions to make the recipe
    instructions = models.TextField()
    # The date this recipe object was created
    creation_date = models.DateField(auto_now_add=True)
    # The ingredient set of ingredients that is required for this recipe
    ingredients = models.ManyToManyField(Ingredient,
                                         through='RecipeIngredient')
    # The appliance set of appliances needed for this recipe
    appliances = models.ManyToManyField(Appliance)
    # If the recipe is a user's private recipe
    is_private = models.BooleanField(default=True)
    # The url from which we scraped this recipe
    source_url = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        """Return a string to identify the object in the admin app."""
        return self.title

    def get_ingredients(self):
        """Return a queryset of the ingredients in this recipe."""
        return self.ingredients.all()

    def get_appliances(self):
        """Return a queryset of the appliances required by this recipe."""
        return self.appliances.all()

    def get_rating(self):
        """Return the average rating for the recipe."""
        return self.userrating_set.all().aggregate(Avg('value'))['value__avg']

    def get_rating_count(self):
        """Return the number of ratings for the recipe."""

recipe/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core import exceptions

from .models import Recipe, RecipeIngredient, Ingredient, Comment

import re


class RecipeForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(RecipeForm, self).__init__(*args, **kwargs)

        for key in self.fields:
            self.fields[key].required = True

    class Meta:
        model = Recipe
        fields = ('title', 'summary', 'difficulty',
                  'time', 'image_url', 'instructions')
        widgets = {
            'title':        forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Recipe Name'}),
            'summary':      forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Description'}),
            'difficulty':   forms.Select(attrs={'class': 'form-control', 'placeholder': 'Difficulty'}),
            'time':         forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Time (Minutes)'}),
            'image_url':    forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'Image URL'}),
            'instructions': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Instructions'}),
        }

    def clean_instructions(self):
        """Clean instructions by escaping unsafe tags with a whitelist."""
        TAG_WHITELIST = ['b', 'strong', 'i', 'em', 'ul', 'ol', 'li', 'br', 'p', 'hr', 'blockquote']

        # Replace all < with &lt; in case the full match fails for a tag
        instructions = self.cleaned_data['instructions'].replace("<", "&lt;")
        # Fix safe tags so they're rendered as html
        for tag in TAG_WHITELIST:
            instructions = re.sub(r'&lt;(?=/?[ \t]*{0}[ \t]*>)'.format(tag), '<', instructions)

        #change new lines to break tags so whitespace is preserved in instructions
        instructions = instructions.replace('\n', '<br>')
        return instructions

    def is_valid(self):
        valid = super(RecipeForm, self).is_valid()

        return valid

class RecipeIngredientForm(forms.ModelForm):
    ingredient = forms.ModelChoiceField(widget=forms.Select(attrs={
                                        'placeholder': 'Ingredient', 'class':'drop-down-ingredient-search'}),
                                        empty_label='--Ingredient--',
                                        queryset=Ingredient.objects)

    class Meta:
        model = RecipeIngredient
        fields = ('ingredient', 'amount', 'unit')
        widgets = {
            'amount': forms.TextInput(attrs={'placeholder': 'Amount (ex: 2 1/2)', 'class': 'form-control ingredient-input'}),
            'unit':   forms.TextInput(attrs={'placeholder': 'Unit (ex: Cups)', 'class': 'form-control ingredient-input'}),
        }

    def is_valid(self):
        valid = super(RecipeIngredientForm, self).is_valid()

        return valid


RecipeIngredientFormSet = forms.inlineformset_factory(Recipe, RecipeIngredient,
                        form=RecipeIngredientForm, extra=10, min_num=1, validate_min=True, can_delete=False)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Comment'})
        }

recipe/templates/recipe/edit_private_recipe.html
{% extends 'base.html' %}

{% block head %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'recipe/addRecipeForm.css' %}" />
<link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.3/chosen.css">
{% endblock %}

{% block content %}
<div class="content">

  <h1 class="text-center m-5">Edit Private Recipe</h1>


  {% for error in form.non_field_errors %}
      <div class="form-group has-errors text-danger text-center">{{error|escape}}</div>
  {% endfor %}

  {% for field in form %}
      {% for error in field.errors %}
          <div class="form-group has-errors text-danger text-center">{{error|escape}}</div>
      {% endfor %}
  {% endfor %}

  <form method="post" class="form-signin">
      {% csrf_token %}

      <!-- Add Recipe form -->
      {% for field in form %}
          <p>
              {{ field }}
          </p>
      {% endfor %}

      <!-- Ingredient forms -->
      {{ formset.management_form }}
      {% for ingredient_form in formset %}
          <!-- Ingredient form errors -->
          {% for ingredient_error in ingredient_form.non_field_errors %}
              <div class="form-group has-errors text-danger text-center">{{ingredient_error|escape}}</div>
          {% endfor %}

          <!-- Ingredient form field -->
          <div class="form-group">
            <!-- Ingredient form field errors -->
            {% for ingredient_field in ingredient_form %}
              {% for ingredient_error in ingredient_field.errors %}
                <p class="form-group has-errors text-danger">{{ingredient_error|escape}}</p>
              {% endfor %}
            {% endfor %}

            <div class="ingredient-field">
              {% for ingredient_field in ingredient_form %}
                  <!-- Ingredient field -->
                  {{ ingredient_field }}
              {% endfor %}
            </div>
          </div>
      {% endfor %}
      <div style="display:flex" class="save-cancel-delete row">
          <button id="submit" type="submit" class="btn btn-dark btn-lg mt-5">Save</button>
          <div class="cancel-delete">
            <a id="cancel" class="btn btn-dark btn-lg mt-5" href="{% url 'recipe:recipe_full_view' recipe_id %}"> Cancel </a>
            <a id="delete" class="btn  btn-lg mt-5" href="{% url 'recipe:delete_recipe_view' recipe_id %}"> Delete </a>
          </div>
      </div>
  </form>
</div>

{% endblock %}

{% block footer %}
  <script src="http://code.jquery.com/jquery-1.8.3.js"></script>
  <script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.3/chosen.jquery.js"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      // Select all single select
      choose = $(".drop-down-ingredient-search");
      // Activate Chosen library
      choose.chosen();
      // Hacks to make menus show up above other elements. It has some issues...
      choose.parent().css('overflow', 'visible');
      choose.closest('.form-row').css('overflow', 'visible');

      if ($(window).width() < 400) {
        $(".cancel-delete").css('position', 'inherit');
      }
    });
  </script>
  <script>
      $(document).on('click', '#cancel', function(){
          return confirm('Any unsaved changes will be discarded.');
      })
      $(document).on('click', '#delete', function(){
          return confirm('This item will not be recoverable.\nAre you sure you still want to delete this?');
      })
  </script>
{% endblock %}

recipe/templates/recipe/favorites.html
{% extends 'base.html' %}

{% block head %}
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'recipe/recipe_summary.css' %}" />
{% endblock %}

{% block content %}
<div class="content">
  <h1>My Favorite Recipes</h1>
  {% if favorites %}
    {% for fav in favorites %}
      <hr />
      <a class="recipe-summary" href="{% url 'recipe:recipe_full_view' fav.recipe.id %}">
        <img alt="recipe image" src="{{fav.recipe.image_url}}"/>
        <div>
          <h3>{{fav.recipe.title}}</h3>
          <p>{{fav.recipe.summary}}</p>
        </div>
      </a>
    {% endfor %}
  {% else %}
    <p>You do not have any favorite recipes.</p>
  {% endif %}
</div>
{% endblock %}

recipe/templates/recipe/index.html
{% extends 'base.html' %}

{% block head %}
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'recipe/slideout.css' %}" />
  <link rel="stylesheet" href="{% static 'recipe/no_ingredients.css' %}" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css" />
  <link rel="stylesheet" href="{% static 'recipe/recipe_summary.css' %}" />
{% endblock %}

{% block slide_out %}
<div class="">
  <button id="run-search" class="toggle-button" type="button" data-toggle="collapse"><img src="{% static 'recipe/images/Hamburger_Button.png' %}" class="hamburger-menu-button"/>
  </button>
</div>
{% endblock %}

{% block precontent %}
  {% include 'recipe/ingredientsmenu.html' %}
{% endblock %}

{% block content %}
  <div id="noIngredients" class="text-center m-5">
    <h1>If you want to search for recipes, please select which ingredients you want to search by.</h1>
    <br />
    <button class="toggle-button btn btn-dark" type="button" data-toggle="collapse">Start Search</button>
  </div>
  <div id="found_recipes" class="content">
    <!-- Javascript inserts recipes here -->
  </div>
  <div id="next_10_button_div" class="text-center m-5">
  </div>

{% endblock %}

{% block footer %}
  {% load staticfiles %}
  <script>
    const URL_ALG_REQUEST = "{% url 'recipe:get_recipes' %}";
    const URL_FULL_VIEW = "{% url 'recipe:recipe_full_view' 0 %}".slice(0,-1); //slice to remove '0'
    const PERSISTENT_INGREDIENTS = {{ persistent_ingredients|safe }};
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/slideout/1.0.1/slideout.min.js"></script>
  <script src="{% static 'recipe/slidefunctionality.js' %}"></script>
  <script src="{% static 'recipe/loadingredients.js' %}"></script>
  <script src="{% static 'recipe/ingredientsmenu.js' %}"></script>
  <script src="{% static 'recipe/next10ingredients.js' %}"></script>
{% endblock %}

recipe/templates/recipe/myRecipes.html
{% extends 'base.html' %}

{% block head %}
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'recipe/recipe_summary.css' %}" />
{% endblock %}

{% block content %}
<div class="content">
  <h1>My Recipes</h1>
  {% if my_recipes %}
    {% for recipe in my_recipes %}
      <hr />
      <a class="recipe-summary" href="{% url 'recipe:recipe_full_view' recipe.id %}">
        <img alt="recipe image" src="{{recipe.image_url}}"/>
        <div>
          <h3>{{recipe.title}}</h3>
          <p>{{recipe.summary}}</p>
        </div>
      </a>
    {% endfor %}
  {% else %}
    <p>You have not added any recipes.</p>
  {% endif %}
</div>
{% endblock %}

recipe/templates/recipe/please_authenticate.html
{% extends 'base.html' %}

{% block head %}
  {% load staticfiles %}
{% endblock %}

{% block content %}
  <div class="content">
    <h1 class="text-center m-5">Add Private Recipe</h1>
    <h3 class="text-center"> Please authenticate your email address to add a private recipe. </h3>
  </div>
{% endblock %}


{% block footer %}

{% endblock %}

recipe/templates/recipe/recipe_full_view.html
{% extends 'base.html' %}

{% block head %}
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'recipe/full_recipe.css' %}" />
  <link rel="stylesheet" href="{% static 'recipe/rating.css' %}" />
{% endblock %}

{% block content %}
{% if current_recipe %}
  <div class="content">
    <img alt="recipe image" src="{{current_recipe.image_url}}" />
    <h1>{{current_recipe.title}}
      {% if current_recipe.user.id == user.id %}
        <a href="{% url 'recipe:edit_private_recipe' current_recipe.id %}"><i class="fas fa-edit fa-xs"></i></a>
      {% endif %}
    </h1>
    <div class="text-center">
      {% if current_recipe.source_url %}
        <a class="source-url" href="{{current_recipe.source_url}}">{{ current_recipe.source_url | truncatechars:50 }}</a>
      {% endif %}
    </div>
    {% if user.is_authenticated %}
      <img id="favorite" src="" class="img-fluid update-image"/>
    {% endif %}
    {% if current_recipe.user.id == user.id %}
        {% if current_recipe.is_private %}
            <button class="btn btn-outline-secondary btn-sm submit-public" onclick="submitPublic('{% url 'recipe:submit_for_public' current_recipe.id %}')" href="{% url 'recipe:submit_for_public' current_recipe.id %}">Submit for Public</button>
        {% endif %}
    {% endif %}
    <div id="share-buttons" class="text-center">
      <!-- Facebook -->
      <a href="http://www.facebook.com/sharer.php?u={{request.build_absolute_uri}}" target="_blank">
          <img src="https://simplesharebuttons.com/images/somacro/facebook.png" alt="Facebook" />
      </a>
      <!-- Google+ -->
      <a href="https://plus.google.com/share?url={{request.build_absolute_uri}}" target="_blank">
          <img src="https://simplesharebuttons.com/images/somacro/google.png" alt="Google" />
      </a>
      <!-- Pinterest -->
      <a href="javascript:void((function()%7Bvar%20e=document.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('charset','UTF-8');e.setAttribute('src','http://assets.pinterest.com/js/pinmarklet.js?r='+Math.random()*99999999);document.body.appendChild(e)%7D)());">
        <img src="https://simplesharebuttons.com/images/somacro/pinterest.png" alt="Pinterest" />
      </a>
      <!-- Email -->
      <a href="mailto:?Subject=Yummy Recipe&amp;Body=I%20saw%20this%20and%20thought%20of%20you!%20 {{request.build_absolute_uri}}">
          <img src="https://simplesharebuttons.com/images/somacro/email.png" alt="Email" />
      </a>
    </div>
    <div id="rating-container" class="text-center">
      <div id="rating-stars">
        <!-- Javascript creates stars -->
      </div>
      <div id="rating-count">
        <!-- Javascript creates count -->
      </div>
    </div>

    <p class="text-center">Time:
      {% if current_recipe.time != None %}
        {{current_recipe.time}} minutes
      {% endif %}
      <span class="spacing"></span> Difficulty:
      {% if current_recipe.get_difficulty_display != None %}
        {{current_recipe.get_difficulty_display}}
      {% endif %}
    </p>
    <hr />

    {% if current_recipe.summary != None %}
      <h2>{{current_recipe.summary}}</h2>
    {% endif %}
    <hr />
    {% if ingredients %}
      <div class="ingredients-list text-center">
        {% for ingredient in ingredients %}
          <div>
            <i class="fas fa-caret-right fa-sm"></i>
            {% if ingredient.amount != None %}
              {{ingredient.amount}}
            {% endif %}
            {% if ingredient.unit != None %}
              {{ingredient.unit}}
            {% endif %}
            {% if ingredient.ingredient != None %}
              {{ingredient.ingredient}}
            {% endif %}
          </div>
        {% endfor %}
      </div>
    {% endif %}
    <hr />
    <div class="instructions">
      <p>{{current_recipe.instructions | safe}}</p>
    </div>
  </div>

  <!-- Comment Form -->
  <div class="content">
    <hr />
    {% if user.is_authenticated %}
      <form method="post" class="form-signin">
        <h1 class="text-left">Comment</h1>
        {% csrf_token %}
        <div class="comment-content">
          {{comment_form.content}}
        </div>
        <button type="submit" class="btn btn-dark btn-md mt-5">Submit Comment</button>
      </form>
    {% else %}
      <h3> Please log in to post a comment. </h3>
    {% endif %}


    <!-- Comments -->
    <hr />
    {% for comment in comments %}
      <div class="single-comment">
        <h4>{{comment.user}}</h4>
        <h5>{{comment.creation_date|date}}</h5>
        {{comment.content}}
      </div>
    {% endfor %}

    {% else %}
      <p>Could not load selected recipe.</p>
    {% endif %}
  </div>
{% endblock %}

{% block footer %}
{% load staticfiles %}
<script>
  const URL_RATE = "{% url 'recipe:rate' current_recipe.id %}";
  const URL_FAV = "{% url 'recipe:favorite' current_recipe.id %}";
  const IMG_STAR_FULL = "{% static 'recipe/images/star-full.png' %}";
  const IMG_STAR_FULL_GRAY = "{% static 'recipe/images/star-full-gray.png' %}";
  const IMG_STAR_EMPTY = "{% static 'recipe/images/star-empty.png' %}";
  const IS_FAVORITE = {{ isFavorite }};
  {% if user.is_authenticated %}
  const IS_AUTHENTICATED = true;
  {% else %}
  const IS_AUTHENTICATED = false;
  {% endif %}
</script>
<script src="{% static 'recipe/rating.js' %}"></script>
<script src="{% static 'recipe/favorite.js' %}"></script>
<script src="{% static 'recipe/submit_confirm.js' %}"></script>
{% endblock %}

recipe/templates/recipe/submit_for_public.html
{% extends 'base.html' %}

{% block content %}

<h1> Recipe Submission Successful!</h1>

<p></p>
<p>Your recipe has been submitted to be moved to the public records.</p>
<p>It is now under review by our team of Hippo-Chefs. Please give them time as they consider your offering.<p>
<p></p>
<a class="" href="{% url 'recipe:recipe_full_view' current_recipe %}">Go back to recipe page...</a> 
{% endblock %}