hhh/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^emailauth/', include('emailauth.urls')),
    url(r'^scraper/', include('scraper.urls')),
    url(r'^', include('recipe.urls')),
]

scraper/urls.py
"""Holds the urls for the scraper app. Already prefixed with 'scraper/'."""

from django.conf.urls import url

from . import views

app_name = "scraper"
urlpatterns = [
    url(r'^display/$', views.scrape_and_display, name='scrape_and_display'),
    url(r'^batch/(?P<start>[0-9]+)-(?P<end>[0-9]+)/$', views.scrape_batch, name='scrape_batch'),
    url(r'^scrape/$', views.scrape_and_save, name='scrape_and_save'),
    url(r'^results/(?P<job_id>[0-9]+)/$', views.get_results, name='results'),
    url(r'^results/raw/(?P<job_id>[0-9]+)/$', views.get_results_raw, name='results_raw'),
    url(r'^$', views.scrape, name='scrape')
]

scraper/models.py
"""Holds the models for the scraper."""

from django.db import models

class ScrapeResult(models.Model):
    """Holds the resulting status of scraping a url."""

    # The job that scraped this url
    job_id = models.IntegerField()
    # The date and time when we scraped this url
    scrape_time = models.DateTimeField(auto_now_add=True)
    # The url from which we scraped this recipe
    source_url = models.CharField(max_length=200)
    # Whether the scrape was successful
    successful = models.BooleanField()
    # The type of error that occured
    error_type = models.CharField(max_length=50, null=True, blank=True)
    # An error if there was one
    error = models.CharField(max_length=300, null=True, blank=True)
    # Stack trace of error
    error_trace = models.TextField(null=True, blank=True)
    # Url to saved recipe page if successful
    saved_url = models.CharField(max_length=200, null=True)

    def __str__(self):
        """Display important information to the result."""
        return "{0} : {1}".format(self.successful, self.get_short_error())

    def get_short_error(self):
        """Return a short version of the error."""
        if self.error:
            return self.error[:50]
        return self.error

scraper/views.py
"""Holds the views for the scraper."""

from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from django.utils.html import escape
from django.contrib.admin.views.decorators import staff_member_required
from .utils import scrape_to_json, scrape_and_save
from .job_processor import submit_job
from .models import ScrapeResult

@staff_member_required(login_url='login')
def scrape(request):
    """User interface for the scraper."""
    if request.method == 'GET':
        return render(request, 'scraper/create_job.html')

    # Assume post
    form_errors = []

    site_url = escape(request.POST.get('sample-url', ''))
    start = escape(request.POST.get('id-start', ''))
    count = escape(request.POST.get('id-count', ''))

    if not site_url:
        form_errors.append('Site url invalid or empty')
    if not start:
        form_errors.append('Start invalid or empty')
    if not count:
        form_errors.append('Count invalid or empty')

    end = 0
    if not form_errors:
        try:
            start = int(start)
            end = start + int(count) - 1
        except Exception as e:
            form_errors.append(e)

    if form_errors:
        return render(request, 'scraper/create_job.html', {'errors': form_errors})

    job_errors = []
    job_id = -1
    try:
        job_id = submit_job(site_url, start, end, request.user)
    except Exception as e:
        job_errors.append('Job raised exception: {}'.format(e))

    if job_errors:
        context = {'job_id': job_id, 'errors': job_errors}
        return render(request, 'scraper/job_error.html', context)

    return redirect('scraper:results', job_id=job_id)

@staff_member_required(login_url='login')
def get_results(request, job_id):
    """Return the page to display status of a job."""
    return render(request, 'scraper/job_status.html', {'job_id': job_id})

@staff_member_required(login_url='login')
def get_results_raw(request, job_id):
    """Return the current results of a job."""
    results = ScrapeResult.objects.filter(job_id=job_id).order_by("scrape_time").values()
    return JsonResponse({'results': list(results)})

@staff_member_required(login_url='login')
def scrape_batch(request, start, end):
    """Scrape and save a batch of recipes based on passed parameters."""
    start = int(start)
    end = int(end)
    if start > end:
        return HttpResponse('Start must be less than end')

    site_url = escape(request.GET.get('url', ''))

    try:
        submit_job(site_url, start, end, request.user)
    except Exception as e:
        return HttpResponse('Job threw unexpected error: {}'.format(e))

    return HttpResponse('Job submitted successfully')

@staff_member_required(login_url='login')
def scrape_and_display(request):
    """Return a json object from a given url. URL is specified by '?url=' parameter."""
    return JsonResponse(scrape_to_json(escape(request.GET.get('url', ''))))

@staff_member_required(login_url='login')
def scrape_and_save(request):
    """Parse a url and save it to the database."""
    return HttpResponse(scrape_and_save(escape(request.GET.get('url', '')), request.user))

scraper/templates/scraper/create_job.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center m-5">Recipe Scraper</h1>

{% for error in errors %}
  <div class="form-group text-danger text-center">{{ error | escape }}</div>
{% endfor %}

<form method="post">
  {% csrf_token %}
  <div class="form-group">
    <label for="sample-url">Sample url to scrape:</label>
    <input type="url" class="form-control" name="sample-url" placeholder="http://www.allrecipes.com" aria-describedby="sample-url-help" value="http://www.allrecipes.com" required />
    <small id="sample-url-help" class="form-text text-muted">Only the hostname is grabbed to determine the scraper and website. (Make sure you include the protocol)</small>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="id-start">Starting id:</label>
      <input type="number" class="form-control" name="id-start" placeholder="" aria-describedby="id-start-help" min="0" required />
      <small id="id-start-help" class="form-text text-muted">The starting recipe id to scrape.</small>
    </div>
    <div class="form-group col-md-6">
      <label for="id-count">Count:</label>
      <input type="number" class="form-control" name="id-count" placeholder="" aria-describedby="id-count-help" min="1" max="200" value="10" />
      <small id="id-count-help" class="form-text text-muted">The number of recipes to scrape.</small>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Submit Batch</button>
</form>
{% endblock %}

scraper/templates/scraper/job_error.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center m-5">Job {{ job_id }} returned with errors:</h1>

{% for error in errors %}
  <div class="form-group text-danger text-center">{{ error | escape }}</div>
{% endfor %}
{% endblock %}

scraper/templates/scraper/job_status.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
<link rel="stylesheet" href="{% static 'scraper/job_status.css' %}" type="text/css" />
{% endblock %}

{% block content %}
<h1 class="text-center m-5">Job {{ job_id }} status</h1>

<table class="table table-hover" id="result-status-container"></table>
{% endblock %}

{% block footer %}
<script>
  const JOB_URL = "{% url 'scraper:results_raw' job_id=job_id %}";
</script>
<script src="{% static 'scraper/job_status.js' %}"></script>
{% endblock %}