accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/', views.login_view, name='login'),
    url(r'^register/', views.register_view, name='register'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^myrecipes/', views.myrecipes_view, name='myRecipes'),
    url(r'^favorites/', views.favorite_recipes, name='favorites'),
    url(r'^profile/', views.profile, name='profile'),
]

hhh/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^emailauth/', include('emailauth.urls')),
    url(r'^scraper/', include('scraper.urls')),
    url(r'^', include('recipe.urls')),
]

recipe/urls.py
"""Holds the routing information for the recipe app."""

from django.conf.urls import url

from . import views

app_name = "recipe"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_private_recipe$', views.add_private_recipe, name='add_private_recipe'),
    url(r'^edit_private_recipe/(?P<id>[0-9]+)/$', views.edit_private_recipe, name='edit_private_recipe'),
    url(r'^delete_recipe/(?P<id>[0-9]+)/$', views.delete_recipe_view, name='delete_recipe_view'),
    url(r'^recipe_full_view/(?P<id>[0-9]+)/$', views.recipe_full_view, name='recipe_full_view'),
    url(r'^recipe_full_view/(?P<id>[0-9]+)/rate/$', views.rate, name='rate'),
    url(r'^recipe_full_view/(?P<id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^get_recipes/$', views.get_recipes, name='get_recipes'),
    url(r'^submit_for_public/(?P<id>[0-9]+)/$', views.submit_for_public, name='submit_for_public'),
]

accounts/models.py
"""Tables to extend the user functionality."""

from django.db import models
from django.contrib.auth.models import User

class PersistentIngredient(models.Model):
    """Holds the current ingredients a user has selected.

    Allows the user's ingredients to persist across searches and sessions.
    """

    # Holds the user to which this ingredient points
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # Holds the ingredient this user has selected
    ingredient = models.ForeignKey('recipe.Ingredient', on_delete=models.CASCADE)

    def __str__(self):
        """Construct a string representation of this ingredient link."""
        return '{0} : {1}'.format(self.user, self.ingredient)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from django.core import exceptions

class CreateUserForm(forms.Form):

    user_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Username'}), max_length=20)
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Email'}), max_length=50)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}), max_length=20)
    password_verify = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Verify Password'}), max_length=20)

    def is_valid(self):
        valid = super(CreateUserForm, self).is_valid()
        if not valid:
            return valid

        user_name = self.cleaned_data['user_name']
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']
        password_verify = self.cleaned_data['password_verify']

        try:
            validate_password(password, user_name)
        except exceptions.ValidationError as e:
            for error in e.messages:
                self.add_error('password', error)
            valid = False

        if(password != password_verify):
            self.add_error('password_verify', 'Passwords did not match.')
            valid = False

        if(User.objects.filter(username__iexact=user_name)):
            self.add_error('user_name', 'That user already exists!')
            valid = False

        if(User.objects.filter(email__iexact=email)):
            self.add_error('email', 'That email is already being used.')
            valid = False

        return valid

class LoginForm(forms.Form):
    user_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Username'}), max_length=20)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}), max_length=20)

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from emailauth import models as EA_models

from .forms import CreateUserForm, LoginForm
from emailauth.views import sendAuthEmail
from recipe.models import Recipe, RecipeIngredient, Favorite


def login_view(request):
    """View for when the user goes to the login page."""
    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            user_name = form.cleaned_data['user_name']
            password = form.cleaned_data['password']

            user = authenticate(request, username=user_name, password=password)
            if user is not None:
                login(request, user)
                return redirect('recipe:index')
            else:
                form.add_error(None, 'Invalid Username/Password')

    else:
        form = LoginForm()

    context = {'form': form}
    return HttpResponse(render(request, 'accounts/login.html', context))


def register_view(request):
    """View for when the user goes to the creating account page."""
    if request.method == 'POST':
        form = CreateUserForm(request.POST)

        if form.is_valid():
            user_name = form.cleaned_data['user_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            cur_usr = User.objects.create_user(user_name, email, password)
            # adding creation of email_authentication/user relationship step
            # TODO: add EmailAuth creation step, called from models.py
            EA_models.makeEmailAuth(cur_usr, False)

            success_context = {'user_name': user_name, 'email': email}
            user = authenticate(request, username=user_name, password=password)
            if user is not None:
                login(request, user)
            else:
                form.add_error(None, 'Failed to create account')
                context = {'form': form}
                return HttpResponse(render(request, 'accounts/register.html', context))
            # adding authentication email step call
            sendAuthEmail(email)
            return render(request, 'accounts/register_successful.html', success_context)

    else:
        form = CreateUserForm()

    context = {'form': form}
    return HttpResponse(render(request, 'accounts/register.html', context))


def logout_view(request):
    """View for when the user logs out."""
    logout(request)
    response = redirect('recipe:index')
    response.user = request.user
    return response

@login_required
def myrecipes_view(request):
    """View for when the user goes to the My Recipes page."""
    my_recipes = Recipe.objects.filter(user=request.user)
    context = {"my_recipes" : my_recipes}
    return HttpResponse(render(request, 'recipe/myRecipes.html', context))

@login_required
def favorite_recipes(request):
    """View for the Favorites page."""
    favorites = Favorite.objects.filter(user=request.user)
    
    context = {"favorites" : favorites}
    return HttpResponse(render(request, 'recipe/favorites.html', context))

@login_required
def profile(request):
    """View for when the user goes to the Profile page."""
    user = User.objects.get(username=request.user)
    users_recipes = Recipe.objects.filter(user=request.user)[:3]
    users_favorites = Favorite.objects.filter(user=request.user)[:3]
    context = { 'user' : user, 'users_recipes' : users_recipes, 'users_favorites' : users_favorites}
    return HttpResponse(render(request, 'accounts/profile.html', context))

accounts/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css' %}" />
    <link rel="stylesheet" href="{% static 'marquee.css' %}" />
    <title>Hungry Hungry Hippos</title>
    <link rel="icon" href="{% static 'hippo_marquee.png' %}" type="image/gif" sizes="16x16">
    {% block head %}
    {% endblock %}
  </head>
  <body>
    <!--Navbar-->
    <nav class="navbar navbar-dark fixed-top bg-dark navbar-expand-md">
      {% block slide_out %}
      {% endblock %}
      <a class="navbar-brand nav-item nav-link mr-auto page-title" href="{% url 'recipe:index' %}">Hungry Hungry Hippos</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
          <!--TODO: Use JavaScript to reset what is active-->
          {% if user.is_authenticated %}
          <!--User view-->
            <li class="nav-item navbar-brand">
              <span>{{ user.get_username }}</span>
            </li>
            <li class="nav-item">
              <!--TODO: replace # with correct links once they are up and running-->
              <a class="nav-link" href="{% url 'profile' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'favorites' %}">Favorites</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'recipe:add_private_recipe' %}">Add Recipe</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'myRecipes' %}">My Recipes</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
          {% else %}
          <!--Guest view-->
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Create Account</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    {% block precontent %}
    {% endblock %}

    <div id="panel" class="container pt-2">
      {% block content %}
      {% endblock %}
    </div>

    <!--Scripts for Bootstrap-->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'accounts/pageTitle.js' %}"></script>
    {% block footer %}
    {% endblock %}

    <footer>
      <div class="marquee-top"></div>
      <div class="marquee">
        <div>
          {% for i in "12345678901234567890123456789012345678901234567890123456789012345678901234567890" %}
          <img src="{% static 'hippo_marquee.png' %}" />
          {% endfor %}
        </div>
      </div>
    </footer>
  </body>
</html>